# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Microsoft.MSKLC
PackageVersion: "1.4"
PackageLocale: en-US
Publisher: Microsoft
PackageName: Microsoft Keyboard Layout Creator
License: Proprietary
Copyright: Copyright (c) 1999-2019 Igor Pavlov
ShortDescription: The Microsoft Keyboard Layout Creator allows users to create or modify keyboard layouts.
ManifestType: defaultLocale
ManifestVersion: 1.5.0
