# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Microsoft.PowerQuery
PackageVersion: 2.62.5222.761
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Microsoft Power Query for Excel
License: Proprietary
ShortDescription: Microsoft Power Query for Excel is an Excel add-in that enhances the self-service Business Intelligence experience in Excel by simplifying data discovery, access and collaboration.
ManifestType: defaultLocale
ManifestVersion: 1.5.0
